//this file defines 2 arrays for you

var fruit =
  [ 'Apple',
    'Apricot',
    'Banana',
    'Blackberry',
    'Blueberry',
    'Boysenberry',
    'Cantaloupe',
    'Currant',
    'Cherry',
    'Cherimoya',
    'Cloudberry',
    'Coconut',
    'Cranberry',
    'Date',
    'Dragonfruit',
    'Durian',
    'Elderberry',
    'Fig',
    'Gooseberry',
    'Grape',
    'Grapefruit',
    'Guava'];

var vegetables =
  [ 'Artichoke',
    'Arugula',
    'Asparagus',
    'Eggplant',
    'Alfalfa sprouts',
    'Bean sprouts',
    'Black beans',
    'Rutabaga',
    'Turnip',
    'Radish',
    'Turnip',
    'Horseradish',
    'Spinach',
    'Zucchini',
    'Potato',
    'Sweet potato',
    'Water chestnut' ];
